server.port=8082 
spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID_HERE 
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET_HERE 
spring.security.oauth2.client.registration.google.scope=openid,profile,email 
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com 
